BASE_FILE_FOLDER = "/vast/scratch/users/lmcintosh/CN_SV_SNV_evolutionary_likelihood/"
PRECOMPUTED_FILE_FOLDER = BASE_FILE_FOLDER + "PRECOMPUTED/MATRICES/"
SIMULATIONS_FILE_FOLDER = BASE_FILE_FOLDER + "SIMULATIONS"
