

# This file was *autogenerated* from the file collate.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0)
base="/export/share/prkfs2/shared/bioinf-data/Papenfuss_lab/projects/lachlan/PHD/GD_matrices3/precomputed"

from glob import glob
import sys
i = int(sys.argv[_sage_const_1 ])
j = int(sys.argv[_sage_const_2 ])
dimension = int(sys.argv[_sage_const_3 ])
length = int(sys.argv[_sage_const_4 ])
p = sys.argv[_sage_const_5 ]
# iterate over all combinations of u and d and all paths and collate them into one data frame
output = open("/export/share/prkfs2/shared/bioinf-data/Papenfuss_lab/projects/lachlan/PHD/GD_matrices/collated_"+str(i)+"_"+str(j)+"_"+str(dimension)+"_"+p+".csv",'w')
print(i)
print(j)
print(dimension)
print(p)
file_search = base+"/pre_mat"+str(dimension)+"_"+p+"_u"+str(i)+"_d"+str(j)+"/*"
print(file_search)

all_paths = 

for file in glob(file_search,recursive=False):
    print(file)
    file = str(file)
    history = file.split(".precomputed.sobj")[_sage_const_0 ].split(base)[_sage_const_1 ].split("/")[_sage_const_2 ]
    print(file)
    print(history)
    m = load(file)
    line = str(i)+","+str(j)
    line = line+","+history+","
    line = line+",".join([str(RR(x)) for x in m[_sage_const_1 ,:][_sage_const_0 ] ])+"\n"
    output.write(line)
    


