

# This file was *autogenerated* from the file make_combos_adjacent.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3)
import sys

length = int(sys.argv[_sage_const_1 ]) 
base_paths = list(range(_sage_const_0 ,length+_sage_const_1 ))
all_paths = []
for i in base_paths:
    all_paths.append(str(i))

for i in base_paths:
    for j in base_paths:
        if i + j + _sage_const_1  <= length:
            all_paths.append(str(i) + "G" + str(j)) 

for i in base_paths:
    for j in base_paths:
        for k in base_paths:
            if i + j + k + _sage_const_2  <= length:
                all_paths.append(str(i) + "G" + str(j) + "G" + str(k)) 

print(base_paths)
print(len([x for x in all_paths if len(x.split("G")) == _sage_const_1 ]))
print(len([x for x in all_paths if len(x.split("G")) == _sage_const_2 ]))
print(len([x for x in all_paths if len(x.split("G")) == _sage_const_3 ]))
print(len([x for x in all_paths]))

# save the like of all combinations that we wantto make

save(all_paths,"all_path_combinations_p"+str(length)+"_v4")


