

# This file was *autogenerated* from the file precompute_singular.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_100 = Integer(100)

import sys

args = sys.argv
i=int(args[_sage_const_1 ])
j=int(args[_sage_const_2 ])
n=int(args[_sage_const_3 ])
m=load("matrix_"+str(n)+".sobj")
m2 = m.subs(u=i/_sage_const_100 ,d=j/_sage_const_100 )
outfile = "precomputed/pre_mat"+str(n)+"_u"+str(i)+"_d"+str(j)
save(m2,outfile)

